INSERT INTO `profiles` VALUES
                           (81,92,'Chartered accountant at Dyer, English and Acosta','IT','Chartered accountant','Chartered accountant at Dyer, English and Acosta','http://mysite.com',1),
                           (82,93,'Chartered loss adjuster at Williams Group','IT','Chartered loss adjuster','Chartered loss adjuster at Williams Group','http://mysite.com',1),
                           (83,94,'Hospital doctor at Wright LLC','IT','Hospital doctor','Hospital doctor at Wright LLC','http://mysite.com',1),
                           (84,95,'Engineer, electrical at Davis and Sons','IT','Engineer, electrical','Engineer, electrical at Davis and Sons','http://mysite.com',1),
                           (85,96,'Chartered management accountant at Conrad, Ford and Howard','IT','Chartered management accountant','Chartered management accountant at Conrad, Ford and Howard','http://mysite.com',1),
                           (86,97,'Banker at Hernandez-Wilson','IT','Banker','Banker at Hernandez-Wilson','http://mysite.com',1),
                           (87,98,'Accommodation manager at Whitney, Morrison and Gallagher','IT','Accommodation manager','Accommodation manager at Whitney, Morrison and Gallagher','http://mysite.com',1),
                           (88,99,'Purchasing manager at Russo, Schultz and Reilly','IT','Purchasing manager','Purchasing manager at Russo, Schultz and Reilly','http://mysite.com',1),
                           (89,100,'Administrator, charities/voluntary organisations at Velazquez and Sons','IT','Administrator, charities/voluntary organisations','Administrator, charities/voluntary organisations at Velazquez and Sons','http://mysite.com',1),
                           (90,101,'Teacher, music at Parker and Sons','IT','Teacher, music','Teacher, music at Parker and Sons','http://mysite.com',1),
                           (91,102,'Youth worker at Hart, James and Conley','IT','Youth worker','Youth worker at Hart, James and Conley','http://mysite.com',1),
                           (92,103,'Stage manager at Mullins-Martin','IT','Stage manager','Stage manager at Mullins-Martin','http://mysite.com',1),
                           (93,104,'Furniture conservator/restorer at Hahn, Khan and Eaton','IT','Furniture conservator/restorer','Furniture conservator/restorer at Hahn, Khan and Eaton','http://mysite.com',1),
                           (94,105,'Art gallery manager at Bridges-Hamilton','IT','Art gallery manager','Art gallery manager at Bridges-Hamilton','http://mysite.com',1),
                           (95,106,'Armed forces training and education officer at Black, Rodriguez and Brown','IT','Armed forces training and education officer','Armed forces training and education officer at Black, Rodriguez and Brown','http://mysite.com',1),
                           (96,107,'Firefighter at Ortega LLC','IT','Firefighter','Firefighter at Ortega LLC','http://mysite.com',1),
                           (97,108,'Psychotherapist, child at Simpson Ltd','IT','Psychotherapist, child','Psychotherapist, child at Simpson Ltd','http://mysite.com',1),
                           (98,109,'Computer games developer at Armstrong, Bowen and Jordan','IT','Computer games developer','Computer games developer at Armstrong, Bowen and Jordan','http://mysite.com',1),
                           (99,110,'Toxicologist at Martin Inc','IT','Toxicologist','Toxicologist at Martin Inc','http://mysite.com',1),
                           (100,111,'Dramatherapist at Scott PLC','IT','Dramatherapist','Dramatherapist at Scott PLC','http://mysite.com',1);

INSERT INTO `profiles_connections` VALUES
                                       (81,82),
                                       (81,83),
                                       (81,84),
                                       (81,85),
                                       (82,81),
                                       (82,83),
                                       (82,84),
                                       (82,85),
                                       (83,81),
                                       (83,82),
                                       (83,84),
                                       (83,85),
                                       (84,81),
                                       (84,82),
                                       (84,83),
                                       (84,85),
                                       (85,81),
                                       (85,82),
                                       (85,83),
                                       (85,84);

INSERT INTO `skills` VALUES
                         (77,'MariaDB'),
                         (78,'C++'),
                         (79,'Python'),
                         (80,'JavaScript'),
                         (81,'HTML5'),
                         (82,'CSS3'),
                         (83,'Java'),
                         (84,'Ruby'),
                         (85,'Scala'),
                         (86,'Swift'),
                         (87,'PHP'),
                         (88,'SQL'),
                         (89,'GO'),
                         (90,'Perl'),
                         (91,'TypeScript'),
                         (92,'Rust'),
                         (93,'Kotlin'),
                         (94,'R'),
                         (95,'MATLAB');

INSERT INTO `profiles_skills` VALUES
                                  (81,87),
                                  (81,94),
                                  (82,77),
                                  (82,82),
                                  (82,86),
                                  (82,93),
                                  (83,78),
                                  (84,80),
                                  (84,83),
                                  (84,88),
                                  (84,89),
                                  (85,77),
                                  (85,80),
                                  (85,82),
                                  (86,81),
                                  (86,83),
                                  (87,79),
                                  (87,88),
                                  (87,92),
                                  (88,81),
                                  (88,88),
                                  (88,92),
                                  (89,77),
                                  (89,81),
                                  (89,83),
                                  (90,79),
                                  (90,91),
                                  (91,77),
                                  (91,83),
                                  (91,84),
                                  (91,90),
                                  (91,93),
                                  (92,80),
                                  (93,80),
                                  (93,82),
                                  (93,87),
                                  (93,89),
                                  (93,94),
                                  (94,81),
                                  (94,84),
                                  (94,93),
                                  (95,77),
                                  (95,78),
                                  (95,82),
                                  (95,87),
                                  (96,82),
                                  (97,79),
                                  (98,79),
                                  (98,81),
                                  (98,83),
                                  (98,84),
                                  (98,91),
                                  (99,77),
                                  (99,80),
                                  (99,83),
                                  (99,87),
                                  (99,95),
                                  (100,77),
                                  (100,86),
                                  (100,89),
                                  (100,91);

INSERT INTO `experiences` VALUES
                              (1,92,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (2,92,'Dev','Facebook','San Fran','2013-10-01','2014-11-01'),
                              (3,93,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (4,94,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (5,95,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (6,96,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (7,97,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (8,98,'Dev','Google','San Fran','2010-10-01','2012-11-01'),
                              (9,99,'Dev','Google','San Fran','2010-10-01','2012-11-01');

INSERT INTO `educations` VALUES
                            (29,91,'EPHEC','Graduat','IT','1989-09-01','1991-09-01'),
                            (30,97,'EPHEC','Graduat','IT','1989-09-01','1991-09-01'),
                            (31,92,'Ecole-IT','Master','IT','1989-09-01','1991-09-01'),
                            (32,93,'Ecole-IT','Master','IT','1989-09-01','1991-09-01'),
                            (33,94,'Ecole-IT','Master','IT','1989-09-01','1991-09-01'),
                            (34,95,'Ecole-IT','Master','IT','1989-09-01','1991-09-01'),
                            (35,96,'Ecole-IT','Master','IT','1989-09-01','1991-09-01');