
###
GET http://localhost:8082/connections

###
GET http://localhost:8082/profiles/92/connections

###
POST http://localhost:8082/profiles/80/connections?otherUserId=96

###
DELETE http://localhost:8082/profiles/96/connections?otherUserId=95
